

# This file was *autogenerated* from the file epnc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
sage.repl.load.load(sage.repl.load.base64.b64decode("cG5jLnNhZ2U="),globals(),False)

class EPNC :
    pi = None
    sig = None

    def __init__(self, pi, sig) :
        self.pi = pi
        self.sig = sig
    
    def is_epnc (self) :
        pi = self.pi
        sig = self.sig
        if not is_pnc (pi) :
            return False
        c = pi.base_set_cardinality ()
        n = len (sig)
        if c != n :
            return False
        for b in pi :
            for i, e in enumerate (b) :
                if i < n - _sage_const_1  :
                    if sig [i] > sig [i + _sage_const_1 ] :
                        return False
        return True
    
    def rang (self) :
        return len (self.pi) - _sage_const_1 

