

# This file was *autogenerated* from the file tests_pnc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0)
sage.repl.load.load(sage.repl.load.base64.b64decode("cG5jLnNhZ2U="),globals(),False)

# TESTS PNC
print ("Tests PNC")

P1 = SetPartition ([{_sage_const_1 , _sage_const_5 }, {_sage_const_2 }, {_sage_const_3 , _sage_const_4 }])
P2 = SetPartition ([{_sage_const_1 , _sage_const_3 , _sage_const_4 }, {_sage_const_2 }, {_sage_const_5 }])
P3 = SetPartition ([{_sage_const_1 , _sage_const_3 , _sage_const_4 }, {_sage_const_2 , _sage_const_5 }])
print (is_pnc (P1))
print (is_pnc (P2))
print (is_pnc (P3))
print ()

n = _sage_const_5 
g = generate_pnc (n)
k = _sage_const_0 
for e in g :
    print (e)
    k = k + _sage_const_1 
print (k)
print (catalan_number (n))
print ()

P4 = SetPartition ([{_sage_const_1 , _sage_const_4 }, {_sage_const_2 }, {_sage_const_3 }, {_sage_const_5 }])
P5 = SetPartition ([{_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 }, {_sage_const_5 }])
print (couvre_pnc (P4, P2))
print (couvre_pnc (P4, P3))
print (couvre_pnc (P4, P5))
print (couvre_pnc (P4, P4))
print ()

print (pnc_to_perm (P1))
print ()

print (Kreweras (P1))
print ()

print (label (P4, P2))
print ()

tmp = P1
for i in range (_sage_const_5 ) :
    print (Kreweras (Kreweras (tmp)), rot (tmp))
    tmp = rot (tmp)
print ()

tmp = P1
for i in range (_sage_const_5 ) :
    print (rotb (tmp))
    tmp = rotb (tmp)
print ()

print (P1)
print (rot (rotb (P1)))
print (rotb (rot (P1)))

