

# This file was *autogenerated* from the file tests_ddyck.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8)
sage.repl.load.load(sage.repl.load.base64.b64decode("ZGR5Y2suc2FnZQ=="),globals(),False)

# TESTS DDYCK
print ("Tests DDYCK")

W1 = [_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]
W2 = [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 ]
L1 = [_sage_const_1 , _sage_const_9 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_2 , _sage_const_10 , _sage_const_4 , _sage_const_6 , _sage_const_8 ]
L2 = [_sage_const_1 , _sage_const_2 ]
dd1 = DDYCK (W1, L1)
dd2 = DDYCK (W2, L2)
print (dd1.is_ddyck ())
print (dd2.is_ddyck ())
print ()

P3 = ParkingFunction ([_sage_const_1 , _sage_const_3 , _sage_const_2 , _sage_const_6 , _sage_const_2 , _sage_const_8 , _sage_const_2 , _sage_const_10 , _sage_const_1 , _sage_const_4 ])
dd3 = fp_to_ddyck (P3)
dd3.pretty_print ()
print ()

dd3.flat_print ()
print ()

print (blocks (dd3))
print (ddyck_to_fp (dd3))
print ()

print (dd3.to_list ())
print ()

W4 = [_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]
L4 = [_sage_const_1 , _sage_const_9 , _sage_const_3 , _sage_const_5 , _sage_const_2 , _sage_const_7 , _sage_const_10 , _sage_const_4 , _sage_const_6 , _sage_const_8 ]
dd4 = DDYCK (W4, L4)
dd5 = DDYCK (W1, L4)
dd6 = DDYCK (W4, L1)
print (couvre_ddyck (dd1, dd4))
print (couvre_ddyck (dd1, dd5))
print (couvre_ddyck (dd1, dd6))
print (couvre_ddyck (dd6, dd1))

