

# This file was *autogenerated* from the file tests_eff_pnc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8)
sage.repl.load.load(sage.repl.load.base64.b64decode("ZWZmX3BuYy5zYWdl"),globals(),False)

# TESTS EFF_PNC
print ("Tests eff_pnc")

m1 = {_sage_const_1  : _sage_const_3 , _sage_const_3  : _sage_const_4 , _sage_const_7  : _sage_const_1 }
m2 = {_sage_const_2  : _sage_const_3 , _sage_const_3  : _sage_const_4 , _sage_const_8  : _sage_const_1 }
E1 = EFFPNC (m1)
E2 = EFFPNC (m2)
print (E1.is_eff_pnc ())
print (E2.is_eff_pnc ())
print ()

P1 = E1.to_pnc ()
P2 = E2.to_pnc ()
print (P1)
print (P2)
print ()

print (E1.sizes)
E3 = pnc_to_eff (P1)
print (E3.sizes)
print ()

m4 = {_sage_const_1  : _sage_const_4 , _sage_const_3  : _sage_const_4 }
m5 = {_sage_const_1  : _sage_const_8 , _sage_const_7  : _sage_const_1 }
m6 = {_sage_const_3  : _sage_const_7 , _sage_const_7  : _sage_const_1 }
E4 = EFFPNC (m4)
E5 = EFFPNC (m5)
E6 = EFFPNC (m6)
print (couvre_eff_pnc (E1, E4))
print (couvre_eff_pnc (E4, E1))
print (couvre_eff_pnc (E1, E5))
print (couvre_eff_pnc (E1, E6))
print ()

print (Kreweras_eff (E1))

