

# This file was *autogenerated* from the file tests_edelman_two.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0)
sage.repl.load.load(sage.repl.load.base64.b64decode("ZWRlbG1hbl90d28uc2FnZQ=="),globals(),False)

P1 = [([_sage_const_1 , _sage_const_5 , _sage_const_6 ], [_sage_const_2 , _sage_const_4 , _sage_const_6 ]),
      ([_sage_const_2 , _sage_const_4 ], [_sage_const_3 , _sage_const_5 ]),
      ([_sage_const_3 ], [_sage_const_1 ])]
P2 = [([_sage_const_1 , _sage_const_4 , _sage_const_6 ], [_sage_const_2 , _sage_const_4 , _sage_const_6 ]),
      ([_sage_const_2 , _sage_const_5 ], [_sage_const_3 , _sage_const_5 ]),
      ([_sage_const_3 ], [_sage_const_1 ])]
P3 = [([_sage_const_1 , _sage_const_5 , _sage_const_6 ], [_sage_const_2 , _sage_const_4 , _sage_const_5 ]),
      ([_sage_const_2 , _sage_const_4 ], [_sage_const_3 , _sage_const_3 ]),
      ([_sage_const_3 ], [_sage_const_1 ])]
P4 = [([_sage_const_1 , _sage_const_5 , _sage_const_6 ], [_sage_const_2 , _sage_const_4 , _sage_const_6 ]),
      ([_sage_const_2 , _sage_const_4 ], [_sage_const_5 ]),
      ([_sage_const_3 ], [_sage_const_3 , _sage_const_1 ])]
print (is_edeltwo (P1))
print (is_edeltwo (P2))
print (is_edeltwo (P3))
print (is_edeltwo (P4))
print ()

P5 = [([_sage_const_1 , _sage_const_6 ], [_sage_const_4 , _sage_const_6 ]),
      ([_sage_const_2 , _sage_const_4 ], [_sage_const_3 , _sage_const_5 ]),
      ([_sage_const_3 ], [_sage_const_1 ]),
      ([_sage_const_5 ], [_sage_const_2 ])]
P6 = [([_sage_const_1 , _sage_const_6 ], [_sage_const_4 , _sage_const_6 ]),
      ([_sage_const_2 ], [_sage_const_5 ]),
      ([_sage_const_3 ], [_sage_const_1 ]),
      ([_sage_const_4 ], [_sage_const_3 ]),
      ([_sage_const_5 ], [_sage_const_2 ])]
print (cov_edeltwo (P1, P5))
print (cov_edeltwo (P5, P1))
print (cov_edeltwo (P1, P6))
print ()

n = _sage_const_4 
g = generate_edeltwo (n)
k = _sage_const_0 
for e in g :
    k = k + _sage_const_1 
print (k)
print (cpt_edeltwo (n))
print ()

P7 = [([_sage_const_1 ], [_sage_const_3 ]),
      ([_sage_const_2 , _sage_const_5 ], [_sage_const_1 , _sage_const_4 ]),
      ([_sage_const_3 , _sage_const_4 ], [_sage_const_2 , _sage_const_5 ])]
g = L_pi (P7)
for e in g :
    print (e)
print ()

print (type (P1))
print (type (P7))
print ()

s = [_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]
g = generate_edeltwo_s (s)
k = _sage_const_0 
for e in g :
    print (e)
    k = k + _sage_const_1 
print (k)
print (cpt_edeltwo_s (s))
print ()

A1 = [[_sage_const_1 , _sage_const_5 , _sage_const_6 ], [_sage_const_2 , _sage_const_4 ], [_sage_const_3 ]]
A7 = [[_sage_const_1 ], [_sage_const_2 , _sage_const_5 ], [_sage_const_3 , _sage_const_4 ]]
print (type_pnc (A1))
print (type_pnc (A7))
print ()

s2 = [_sage_const_3 , _sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]
g = generate_pnc_s (s2)
k = _sage_const_0 
for e in g :
    k = k + _sage_const_1 
print (k)
print (cpt_pnc_s (s2))
print ()

s3 = [_sage_const_2 , _sage_const_2 , _sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]
g = generate_part_s (s3)
k = _sage_const_0 
for e in g :
    k = k + _sage_const_1 
print (k)
print (cpt_part_s (s3))
print ()

print (cpt_edeltwo_s (s))
print (cpt_edeltwo_s_alt (s))
print ()

m = _sage_const_5 
h = _sage_const_2 
g = generate_edeltwo_h (m, h)
k = _sage_const_0 
for e in g :
    k = k + _sage_const_1 
print (k)
print (cpt_edeltwo_h (m, h))

