

# This file was *autogenerated* from the file cfp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
sage.repl.load.load(sage.repl.load.base64.b64decode("ZnAuc2FnZQ=="),globals(),False)

class CFP :
    C = []
    k = _sage_const_0 

    def __init__(C) :
        self.C = C
        self.k = len (C)
    
    def is_k_CFP (self, k0) :
        C = self.C
        k = self.k
        if k != k0 :
            return False
        

