

# This file was *autogenerated* from the file ../tests/tests_perm.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_6 = Integer(6)
sage.repl.load.load(sage.repl.load.base64.b64decode("Li4vY29kZS9wZXJtLnNhZ2U="),globals(),False)

# Tests Perm
print ("Tests Perm")

L1 = [_sage_const_1 , _sage_const_5 , _sage_const_2 , _sage_const_4 , _sage_const_3 ]
L2 = [_sage_const_1 , _sage_const_3 , _sage_const_2 , _sage_const_4 , _sage_const_2 ]
print (is_perm (L1))
print (is_perm (L2))
print ()

Lc = [_sage_const_2 , _sage_const_5 , _sage_const_4 , _sage_const_1 , _sage_const_3 ]
print (is_cyclic (L1))
print (is_cyclic (Lc))
print ()

print (inv_perm (L1))
print ()

L3 = [_sage_const_5 , _sage_const_1 , _sage_const_3 , _sage_const_2 , _sage_const_4 ]
print (comp_perm (L1, L3))
print (comp_perm (L1, inv_perm (L1)))
print ()

R  = blocs_perm (L3)
for e in R :
    print (list (e))
print ()

n = _sage_const_4 
g = generate_perm (n)
k = _sage_const_0 
for e in g :
    print (e)
    k = k + _sage_const_1 
print (k)
print (factorial (n))
print ()

L4 = [_sage_const_7 , _sage_const_3 , _sage_const_8 , _sage_const_5 , _sage_const_1 , _sage_const_2 , _sage_const_6 , _sage_const_4 ]
L5 = [_sage_const_1 , _sage_const_5 , _sage_const_2 , _sage_const_3 , _sage_const_4 ]
L6 = [_sage_const_1 , _sage_const_3 , _sage_const_2 , _sage_const_4 , _sage_const_5 ]
print (code (L4))
print (code (L1))
print (code (L5))
print (code (L6))
print ()

print (couvre_perm (L1, L6))
print (couvre_perm (L1, L5))

