

# This file was *autogenerated* from the file ../tests/tests_dyckfp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6)
sage.repl.load.load(sage.repl.load.base64.b64decode("Li4vY29kZS9keWNrZnAuc2FnZQ=="),globals(),False)

# TESTS DYCKFP
print ("Tests DYCKFP")

L1 = [_sage_const_1 , _sage_const_1 , _sage_const_3 , _sage_const_3 , _sage_const_5 , _sage_const_6 , _sage_const_6 , _sage_const_6 ]
D1 = fpp_to_dyck (L1)
print (D1)
pretty_print_dfp (D1)
print ()

L2 = dyck_to_fpp (D1)
print (L1)
print (L2)
print ()

L3 = [_sage_const_6 , _sage_const_1 , _sage_const_5 , _sage_const_3 , _sage_const_1 , _sage_const_6 , _sage_const_6 , _sage_const_3 ]
D3 = fp_to_ddyck (L3)
D3.pretty_print ()
print ()

L4 = ddyck_to_fp (D3)
print (L3)
print (L4)

