

# This file was *autogenerated* from the file pnc.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
sage.repl.load.load(sage.repl.load.base64.b64decode("cGVybS5zYWdl"),globals(),False)

def is_pnc (P) :
    L = []
    for b in P :
        for e in b :
            L.append (e)
    n = len (L)
    L2 = [i for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,n))]
    if not (sorted (L) == L2) :
        return False

    S = Subsets (P, _sage_const_2 )
    for e1, e2 in S :
        S1 = Subsets (e1, _sage_const_2 )
        S2 = Subsets (e2, _sage_const_2 )
        for a, b in S1 :
            for c, d in S2 :
                if a < c and c < b and b < d :
                    return False
                if c < a and a < d and d < b :
                    return False
    return True

def generate_pnc (n) :
    k = _sage_const_0 
    L = SetPartitions (n).list ()
    for p in L :
        if is_pnc (p) :
            k = k + _sage_const_1 
            yield p
    print (k)

def couvre_pnc (P1, P2) :
    S = Subsets (P1, _sage_const_2 )
    for e1, e2 in S :
        for e3 in P2 :
            if e3 == e1.union (e2) :
                P2_ = copy (P2)
                P2_.remove (e3)
                P1_ = copy (P1)
                P1_.remove (e1)
                P1_.remove (e2)
                if (P1_ == P2_) :
                    return True
    return False

def pnc_to_perm (P) :
    if not is_pnc (P) :
        return []
    n = _sage_const_0 
    for b in P :
        n = n + len (list (b))
    P2 = [_sage_const_0 ] * n
    for b in P :
        L = list (b)
        n = len (L)
        for (i, e) in enumerate (L) :
            if i == n - _sage_const_1  :
                P2[e - _sage_const_1 ] = L [_sage_const_0 ]
            else :
                P2 [e - _sage_const_1 ] = L [i + _sage_const_1 ]
    return P2

